import type { GameConfiguration } from "../interfaces/GameConfiguration.js";

export const mtgGameConfig: GameConfiguration = {
  gameCode: "MTG",
  displayName: "Magic: The Gathering",
  market: {
    releaseTier: "R2",
    primaryMarket: "BR",
    liquidityHypothesis: "Modelo Lorcana se repete em MTG (massa crítica maior)",
    watchlistTargetSize: 30,
    catalogProviderId: "scryfall",
  },
  capabilities: {
    foil: true,
    etched: true,
    serialized: true,
    reverseHolo: false,
    collectorNumber: true,
    multiLanguageListings: true,
    competitiveFormats: true,
    commanderStyle: true,
    enchantedStyleRarities: false,
    sealedProduct: false,
  },
  rarities: [
    { value: "common", label: "Common", color: "#9CA3AF" },
    { value: "uncommon", label: "Uncommon", color: "#22C55E" },
    { value: "rare", label: "Rare", color: "#3B82F6" },
    { value: "mythic", label: "Mythic", color: "#EF4444" },
    { value: "special", label: "Special", color: "#F59E0B" },
    { value: "bonus", label: "Bonus", color: "#8B5CF6" },
  ],
  languages: [
    { value: "en", label: "English" },
    { value: "pt", label: "Português" },
    { value: "jp", label: "日本語" },
    { value: "es", label: "Español" },
    { value: "fr", label: "Français" },
    { value: "de", label: "Deutsch" },
  ],
  conditions: [
    { value: "NM", label: "Near Mint" },
    { value: "LP", label: "Lightly Played" },
    { value: "MP", label: "Moderately Played" },
    { value: "HP", label: "Heavily Played" },
    { value: "DM", label: "Damaged" },
  ],
  finishes: [
    { value: "nonfoil", label: "Non-foil" },
    { value: "foil", label: "Foil" },
    { value: "etched", label: "Etched" },
    { value: "serialized", label: "Serialized" },
  ],
  formats: [
    { value: "commander", label: "Commander" },
    { value: "modern", label: "Modern" },
    { value: "legacy", label: "Legacy" },
    { value: "standard", label: "Standard" },
    { value: "pioneer", label: "Pioneer" },
  ],
  watchlistCardNames: [
    "Sol Ring",
    "Cyclonic Rift",
    "Rhystic Study",
    "Lightning Bolt",
    "Force of Will",
    "Brainstorm",
  ],
  searchSynonyms: {
    bolt: ["lightning bolt"],
    sol: ["sol ring"],
    rift: ["cyclonic rift"],
    rhystic: ["rhystic study"],
    fow: ["force of will"],
    brainstorm: ["brainstorm"],
    swords: ["swords to plowshares"],
    counterspell: ["counterspell"],
  },
  filterFacets: [
    {
      id: "finish",
      label: "Acabamento",
      options: [
        { value: "nonfoil", label: "Non-foil" },
        { value: "foil", label: "Foil" },
        { value: "etched", label: "Etched" },
        { value: "serialized", label: "Serialized" },
      ],
    },
    {
      id: "format",
      label: "Formato",
      options: [
        { value: "commander", label: "Commander" },
        { value: "modern", label: "Modern" },
        { value: "legacy", label: "Legacy" },
      ],
    },
  ],
  sellerWizardCopy: {
    searchPlaceholder: "Buscar carta MTG (ex.: Sol Ring)",
    conditionHint: "Condição da single Magic",
    finishHint: "Non-foil, Foil, Etched ou Serialized",
    emptyInventoryHint: "Publique staples Commander/Modern da watchlist MTG",
  },
};
