"""Taxonomia PT-BR do catálogo mestre."""

OFFICIAL_TAXONOMY = {
    "SEALED_PRODUCT": {
        "label": "Produtos selados",
        "subcategories": [
            "BOOSTER_BOX",
            "BOOSTER_PACK",
            "PLAY_BOOSTER",
            "COLLECTOR_BOOSTER",
            "DRAFT_BOOSTER",
            "STARTER_DECK",
            "COMMANDER_DECK",
            "STRUCTURE_DECK",
            "PRERELEASE_KIT",
            "PRERELEASE_PACK",
            "BUNDLE",
            "GIFT_BUNDLE",
            "ELITE_TRAINER_BOX",
            "GIFT_BOX",
            "GIFT_SET",
            "GIFT_COLLECTION",
            "TROVE",
            "ILLUMINEERS_TROVE",
            "COLLECTION_BOX",
            "PREMIUM_COLLECTION",
            "SPECIAL_COLLECTION",
            "POSTER_COLLECTION",
            "DOUBLE_PACK",
            "MINI_TIN",
            "TIN",
            "BUILD_AND_BATTLE",
            "LEAGUE_BATTLE_DECK",
            "BATTLE_DECK",
            "TRAINER_TOOLKIT",
            "UPC",
            "BLISTER",
            "SECRET_LAIR",
            "SPELLBOOK",
            "JUMPSTART",
            "STARTER_KIT",
            "QUEST",
            "ILLUMINEERS_QUEST",
            "HISTORY_PACK",
            "ARMORY_DECK",
            "BLITZ_DECK",
            "CLASSIC_BATTLES",
            "SPOTLIGHT_DECK",
            "SPEED_DUEL",
            "COLLECTOR_BOX",
            "ADVANCED_DECK",
            "TOURNAMENT_KIT",
            "ACCESSORIES_BUNDLE",
        ],
    },
    "SLEEVES": {
        "label": "Sleeves",
        "subcategories": [
            "STANDARD_MATTE",
            "DUAL_MATTE",
            "ART_SLEEVES",
            "JAPANESE_SIZE",
            "PERFECT_FIT",
            "OUTER_SLEEVES",
            "BOARD_GAME",
        ],
    },
    "DECK_BOX": {
        "label": "Deck Box",
        "subcategories": [
            "PLASTIC",
            "PREMIUM",
            "MAGNETIC",
            "FLIP",
            "TWIN",
            "CONVERTIBLE",
            "DECK_CASE",
            "STORAGE_BOX",
            "BOOSTER_STORAGE",
            "ACRYLIC_BOX",
        ],
    },
    "BINDER": {
        "label": "Pastas",
        "subcategories": [
            "ZIP",
            "RING_BINDER",
            "PREMIUM_BINDER",
            "PORTFOLIO",
            "POCKET_ALBUM",
        ],
    },
    "BINDER_PAGE": {
        "label": "Páginas",
        "subcategories": ["POCKET_9", "POCKET_12", "POCKET_18", "SIDE_LOADING", "DIVIDER"],
    },
    "DICE": {
        "label": "Dados",
        "subcategories": ["D6", "D20", "RPG_SET", "METAL_DICE", "DICE_TRAY"],
    },
    "COUNTERS": {
        "label": "Marcadores",
        "subcategories": [
            "ACRYLIC",
            "GLASS",
            "PLASTIC",
            "LORE_COUNTER",
            "POISON_MARKER",
            "SHIELD_MARKER",
            "DAMAGE_COUNTER",
            "LIFE_COUNTER",
            "TOKEN",
            "TOP_LOADER",
            "MAGNETIC_CASE",
            "MINI_SNAP",
            "DISPLAY_STAND",
            "BOARD_GAME_ACCESSORIES",
            "OTHER",
        ],
    },
    "PLAYMAT": {
        "label": "Playmats",
        "subcategories": ["STANDARD", "STITCHED", "PREMIUM_XL", "PLAYMAT_TUBE"],
    },
}
