UPDATE tcg_judge.card_catalog c
SET game_data = COALESCE(c.game_data, '{}'::jsonb)
  || jsonb_build_object('ink', v.ink, 'colors', v.colors)
FROM (VALUES
('ARI', '1', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ARI', '2', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ARI', '3', 'Amber', '["Amber"]'::jsonb),
('ARI', '4', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ARI', '5', 'Amber', '["Amber"]'::jsonb),
('ARI', '6', 'Amber', '["Amber"]'::jsonb),
('ARI', '7', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ARI', '8', 'Amber', '["Amber"]'::jsonb),
('ARI', '9', 'Amber', '["Amber"]'::jsonb),
('ARI', '10', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ARI', '11', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ARI', '12', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ARI', '13', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ARI', '14', 'Amber', '["Amber"]'::jsonb),
('ARI', '15', 'Amber', '["Amber"]'::jsonb),
('ARI', '16', 'Amber', '["Amber"]'::jsonb),
('ARI', '17', 'Amber', '["Amber"]'::jsonb),
('ARI', '18', 'Amber', '["Amber"]'::jsonb),
('ARI', '19', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ARI', '20', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ARI', '21', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ARI', '22', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ARI', '23', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ARI', '24', 'Amber', '["Amber"]'::jsonb),
('ARI', '25', 'Amber', '["Amber"]'::jsonb),
('ARI', '26', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ARI', '27', 'Amber', '["Amber"]'::jsonb),
('ARI', '28', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ARI', '29', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ARI', '30', 'Amber', '["Amber"]'::jsonb),
('ARI', '31', 'Amber', '["Amber"]'::jsonb),
('ARI', '32', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ARI', '33', 'Amber', '["Amber"]'::jsonb),
('ARI', '34', 'Amber', '["Amber"]'::jsonb),
('ARI', '35', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ARI', '36', 'Amber', '["Amber"]'::jsonb),
('ARI', '37', 'Amber', '["Amber"]'::jsonb),
('ARI', '38', 'Amber', '["Amber"]'::jsonb),
('ARI', '39', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ARI', '40', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ARI', '41', 'Amber', '["Amber"]'::jsonb),
('ARI', '42', 'Amber', '["Amber"]'::jsonb),
('ARI', '43', 'Amber', '["Amber"]'::jsonb),
('ARI', '44', 'Amber', '["Amber"]'::jsonb),
('ARI', '45', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '46', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '47', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '48', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '49', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '50', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '51', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ARI', '52', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ARI', '53', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ARI', '54', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ARI', '55', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '56', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '57', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ARI', '58', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '59', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '60', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '61', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '62', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '63', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ARI', '64', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ARI', '65', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ARI', '66', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ARI', '67', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ARI', '68', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ARI', '69', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ARI', '70', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '71', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ARI', '72', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ARI', '73', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '74', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '75', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '76', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '77', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '78', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '79', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ARI', '80', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '81', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '82', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '83', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ARI', '84', 'Amethyst', '["Amethyst"]'::jsonb),
('ARI', '85', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '86', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '87', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '88', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '89', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '90', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '91', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '92', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '93', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '94', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ARI', '95', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ARI', '96', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ARI', '97', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ARI', '98', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '99', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '100', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '101', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '102', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '103', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ARI', '104', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ARI', '105', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ARI', '106', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ARI', '107', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ARI', '108', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '109', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ARI', '110', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '111', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '112', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '113', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '114', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ARI', '115', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '116', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '117', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '118', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '119', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ARI', '120', 'Emerald', '["Emerald"]'::jsonb),
('ARI', '121', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '122', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '123', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '124', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ARI', '125', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '126', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ARI', '127', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '128', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '129', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '130', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '131', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '132', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ARI', '133', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ARI', '134', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '135', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '136', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ARI', '137', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ARI', '138', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '139', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '140', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '141', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ARI', '142', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '143', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '144', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '145', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '146', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '147', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '148', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '149', 'Ruby', '["Ruby"]'::jsonb),
('ARI', '150', 'Ruby', '["Ruby"]'::jsonb)
) AS v(set_code, card_number, ink, colors)
WHERE c.game_code = 'LORCANA'
  AND UPPER(c.set_code) = v.set_code
  AND regexp_replace(COALESCE(c.card_number::text, ''), '^0+', '') = v.card_number;
