UPDATE tcg_judge.card_catalog c
SET game_data = COALESCE(c.game_data, '{}'::jsonb)
  || jsonb_build_object('ink', v.ink, 'colors', v.colors)
FROM (VALUES
('ROF', '85', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '86', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '87', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '88', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '89', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '90', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '91', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '92', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '93', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '94', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '95', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '96', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '97', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '98', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '99', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '100', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '101', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '102', 'Emerald', '["Emerald"]'::jsonb),
('ROF', '103', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '104', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '105', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '106', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '107', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '108', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '109', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '110', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '111', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '112', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '113', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '114', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '115', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '116', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '117', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '118', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '119', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '120', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '121', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '122', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '123', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '124', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '125', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '126', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '127', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '128', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '129', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '130', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '131', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '132', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '133', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '134', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '135', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '136', 'Ruby', '["Ruby"]'::jsonb),
('ROF', '137', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '138', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '139', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '140', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '141', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '142', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '143', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '144', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '145', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '146', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '147', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '148', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '149', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '150', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '151', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '152', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '153', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '154', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '155', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '156', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '157', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '158', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '159', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '160', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '161', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '162', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '163', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '164', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '165', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '166', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '167', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '168', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '169', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '170', 'Sapphire', '["Sapphire"]'::jsonb),
('ROF', '171', 'Steel', '["Steel"]'::jsonb),
('ROF', '172', 'Steel', '["Steel"]'::jsonb),
('ROF', '173', 'Steel', '["Steel"]'::jsonb),
('ROF', '174', 'Steel', '["Steel"]'::jsonb),
('ROF', '175', 'Steel', '["Steel"]'::jsonb),
('ROF', '176', 'Steel', '["Steel"]'::jsonb),
('ROF', '177', 'Steel', '["Steel"]'::jsonb),
('ROF', '178', 'Steel', '["Steel"]'::jsonb),
('ROF', '179', 'Steel', '["Steel"]'::jsonb),
('ROF', '180', 'Steel', '["Steel"]'::jsonb),
('ROF', '181', 'Steel', '["Steel"]'::jsonb),
('ROF', '182', 'Steel', '["Steel"]'::jsonb),
('ROF', '183', 'Steel', '["Steel"]'::jsonb),
('ROF', '184', 'Steel', '["Steel"]'::jsonb),
('ROF', '185', 'Steel', '["Steel"]'::jsonb),
('ROF', '186', 'Steel', '["Steel"]'::jsonb),
('ROF', '187', 'Steel', '["Steel"]'::jsonb),
('ROF', '188', 'Steel', '["Steel"]'::jsonb),
('ROF', '189', 'Steel', '["Steel"]'::jsonb),
('ROF', '190', 'Steel', '["Steel"]'::jsonb),
('ROF', '191', 'Steel', '["Steel"]'::jsonb),
('ROF', '192', 'Steel', '["Steel"]'::jsonb),
('ROF', '193', 'Steel', '["Steel"]'::jsonb),
('ROF', '194', 'Steel', '["Steel"]'::jsonb),
('ROF', '195', 'Steel', '["Steel"]'::jsonb),
('ROF', '196', 'Steel', '["Steel"]'::jsonb),
('ROF', '197', 'Steel', '["Steel"]'::jsonb),
('ROF', '198', 'Steel', '["Steel"]'::jsonb),
('ROF', '199', 'Steel', '["Steel"]'::jsonb),
('ROF', '200', 'Steel', '["Steel"]'::jsonb),
('ROF', '201', 'Steel', '["Steel"]'::jsonb),
('ROF', '202', 'Steel', '["Steel"]'::jsonb),
('ROF', '203', 'Steel', '["Steel"]'::jsonb),
('ROF', '204', 'Steel', '["Steel"]'::jsonb),
('ROJ', '1', 'Amber', '["Amber"]'::jsonb),
('ROJ', '2', 'Amber', '["Amber"]'::jsonb),
('ROJ', '3', 'Amber', '["Amber"]'::jsonb),
('ROJ', '4', 'Amber', '["Amber"]'::jsonb),
('ROJ', '5', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ROJ', '6', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ROJ', '7', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ROJ', '8', 'Amber', '["Amber"]'::jsonb),
('ROJ', '9', 'Amber', '["Amber"]'::jsonb),
('ROJ', '10', 'Amber', '["Amber"]'::jsonb),
('ROJ', '11', 'Amber', '["Amber"]'::jsonb),
('ROJ', '12', 'Amber', '["Amber"]'::jsonb),
('ROJ', '13', 'Amber', '["Amber"]'::jsonb),
('ROJ', '14', 'Amber', '["Amber"]'::jsonb),
('ROJ', '15', 'Amber', '["Amber"]'::jsonb),
('ROJ', '16', 'Amber', '["Amber"]'::jsonb),
('ROJ', '17', 'Amber', '["Amber"]'::jsonb),
('ROJ', '18', 'Amber', '["Amber"]'::jsonb),
('ROJ', '19', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ROJ', '20', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ROJ', '21', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ROJ', '22', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ROJ', '23', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ROJ', '24', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ROJ', '25', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ROJ', '26', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ROJ', '27', 'Amber, Sapphire', '["Amber", "Sapphire"]'::jsonb),
('ROJ', '28', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ROJ', '29', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ROJ', '30', 'Amber, Steel', '["Amber", "Steel"]'::jsonb)
) AS v(set_code, card_number, ink, colors)
WHERE c.game_code = 'LORCANA'
  AND UPPER(c.set_code) = v.set_code
  AND regexp_replace(COALESCE(c.card_number::text, ''), '^0+', '') = v.card_number;
