UPDATE tcg_judge.card_catalog c
SET game_data = COALESCE(c.game_data, '{}'::jsonb)
  || jsonb_build_object('ink', v.ink, 'colors', v.colors)
FROM (VALUES
('ROJ', '31', 'Amber', '["Amber"]'::jsonb),
('ROJ', '32', 'Amber', '["Amber"]'::jsonb),
('ROJ', '33', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ROJ', '34', 'Amber, Amethyst', '["Amber", "Amethyst"]'::jsonb),
('ROJ', '35', 'Amber', '["Amber"]'::jsonb),
('ROJ', '36', 'Amber', '["Amber"]'::jsonb),
('ROJ', '37', 'Amber', '["Amber"]'::jsonb),
('ROJ', '38', 'Amber', '["Amber"]'::jsonb),
('ROJ', '39', 'Amber, Ruby', '["Amber", "Ruby"]'::jsonb),
('ROJ', '40', 'Amber, Steel', '["Amber", "Steel"]'::jsonb),
('ROJ', '41', 'Amber, Emerald', '["Amber", "Emerald"]'::jsonb),
('ROJ', '42', 'Amber', '["Amber"]'::jsonb),
('ROJ', '43', 'Amber', '["Amber"]'::jsonb),
('ROJ', '44', 'Amber', '["Amber"]'::jsonb),
('ROJ', '45', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '46', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '47', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ROJ', '48', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ROJ', '49', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ROJ', '50', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ROJ', '51', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '52', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '53', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '54', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '55', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '56', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '57', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '58', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '59', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '60', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '61', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '62', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '63', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '64', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '65', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '66', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ROJ', '67', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ROJ', '68', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ROJ', '69', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ROJ', '70', 'Amethyst, Ruby', '["Amethyst", "Ruby"]'::jsonb),
('ROJ', '71', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ROJ', '72', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ROJ', '73', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ROJ', '74', 'Amethyst, Steel', '["Amethyst", "Steel"]'::jsonb),
('ROJ', '75', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '76', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '77', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '78', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '79', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '80', 'Amethyst, Emerald', '["Amethyst", "Emerald"]'::jsonb),
('ROJ', '81', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ROJ', '82', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '83', 'Amethyst', '["Amethyst"]'::jsonb),
('ROJ', '84', 'Amethyst, Sapphire', '["Amethyst", "Sapphire"]'::jsonb),
('ROJ', '85', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '86', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '87', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '88', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '89', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '90', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '91', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '92', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '93', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '94', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '95', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '96', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '97', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '98', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '99', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '100', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '101', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '102', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '103', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ROJ', '104', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ROJ', '105', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ROJ', '106', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ROJ', '107', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ROJ', '108', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ROJ', '109', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ROJ', '110', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ROJ', '111', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ROJ', '112', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '113', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '114', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '115', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '116', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '117', 'Emerald, Ruby', '["Emerald", "Ruby"]'::jsonb),
('ROJ', '118', 'Emerald, Steel', '["Emerald", "Steel"]'::jsonb),
('ROJ', '119', 'Emerald', '["Emerald"]'::jsonb),
('ROJ', '120', 'Emerald, Sapphire', '["Emerald", "Sapphire"]'::jsonb),
('ROJ', '121', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '122', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '123', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ROJ', '124', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '125', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '126', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '127', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '128', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '129', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '130', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '131', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '132', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '133', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '134', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '135', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '136', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '137', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '138', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ROJ', '139', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ROJ', '140', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ROJ', '141', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ROJ', '142', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ROJ', '143', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '144', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '145', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '146', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '147', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '148', 'Ruby, Sapphire', '["Ruby", "Sapphire"]'::jsonb),
('ROJ', '149', 'Ruby, Steel', '["Ruby", "Steel"]'::jsonb),
('ROJ', '150', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '151', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '152', 'Ruby', '["Ruby"]'::jsonb),
('ROJ', '153', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '154', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '155', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '156', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '157', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '158', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '159', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '160', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '161', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '162', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '163', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '164', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '165', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '166', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '167', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '168', 'Sapphire, Steel', '["Sapphire", "Steel"]'::jsonb),
('ROJ', '169', 'Sapphire, Steel', '["Sapphire", "Steel"]'::jsonb),
('ROJ', '170', 'Sapphire, Steel', '["Sapphire", "Steel"]'::jsonb),
('ROJ', '171', 'Sapphire, Steel', '["Sapphire", "Steel"]'::jsonb),
('ROJ', '172', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '173', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '174', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '175', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '176', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '177', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '178', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '179', 'Sapphire', '["Sapphire"]'::jsonb),
('ROJ', '180', 'Sapphire', '["Sapphire"]'::jsonb)
) AS v(set_code, card_number, ink, colors)
WHERE c.game_code = 'LORCANA'
  AND UPPER(c.set_code) = v.set_code
  AND regexp_replace(COALESCE(c.card_number::text, ''), '^0+', '') = v.card_number;
