-- P0 remediation: ensure scheduler columns + bootstrap provider_registry.
BEGIN;

ALTER TABLE product_catalog.provider_registry
  ADD COLUMN IF NOT EXISTS schedule_kind text DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS schedule_expr text,
  ADD COLUMN IF NOT EXISTS next_run_at timestamptz,
  ADD COLUMN IF NOT EXISTS rate_limit_rpm int,
  ADD COLUMN IF NOT EXISTS circuit_open_until timestamptz;

DO $$ BEGIN
  ALTER TABLE product_catalog.provider_registry
    ADD CONSTRAINT provider_registry_schedule_kind_check
    CHECK (schedule_kind IN ('every', 'hourly', 'daily', 'weekly', 'manual'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

INSERT INTO product_catalog.provider_registry (
  provider_id, category, enabled, schedule_kind, next_run_at, last_status, updated_at
) VALUES
  ('scryfall-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('pokemon-tcg-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('lorcana-json-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('one-piece-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('digimon-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('dragon-ball-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('star-wars-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('fab-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('yugioh-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('riftbound-sealed', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('liga-public-image-fallback', 'SEALED_PRODUCT', true, 'hourly', now(), 'bootstrapped', now()),
  ('central-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-sleeves', 'SLEEVES', true, 'daily', now(), 'bootstrapped', now()),
  ('central-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-deckboxes', 'DECK_BOX', true, 'daily', now(), 'bootstrapped', now()),
  ('central-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-binders', 'BINDER', true, 'daily', now(), 'bootstrapped', now()),
  ('central-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-dice', 'DICE', true, 'daily', now(), 'bootstrapped', now()),
  ('central-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-counters', 'COUNTERS', true, 'daily', now(), 'bootstrapped', now()),
  ('central-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('gamegenic-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('dragon-shield-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-guard-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('ultra-pro-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('vault-x-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('bcw-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('kmc-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('arcane-tinmen-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('dex-protection-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('ultimate-sleeve-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('bushiroad-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now()),
  ('bandai-accessories-playmats', 'PLAYMAT', true, 'daily', now(), 'bootstrapped', now())
ON CONFLICT (provider_id) DO UPDATE SET
  category = EXCLUDED.category,
  enabled = true,
  schedule_kind = COALESCE(NULLIF(product_catalog.provider_registry.schedule_kind, 'manual'), EXCLUDED.schedule_kind),
  next_run_at = COALESCE(product_catalog.provider_registry.next_run_at, EXCLUDED.next_run_at),
  updated_at = now();

COMMIT;
