import type { PersonaArchetype } from "./types.ts";

export const ARCHETYPES: Record<PersonaArchetype["id"], PersonaArchetype> = {
  "seller-large": {
    id: "seller-large",
    label: "Seller Large",
    role: "seller",
    behavior: "weeklyPublisher",
    inventoryTarget: 5,
    wishlistSize: 0,
    favoritesSize: 0,
    defaultPlan: "pro",
    profile: {
      publishesPerWeek: 12,
      averageListings: 80,
      averageOrderValueCents: 8900,
      returnsAfterDays: 3,
      favoriteRarity: "any",
      preferredLanguage: "any",
      preferredCondition: "NM",
      foilPreference: "any",
      competitiveFormat: null,
      collectionFocus: ["staples", "sealed"],
    },
  },
  "seller-small": {
    id: "seller-small",
    label: "Seller Small",
    role: "seller",
    behavior: "casualSeller",
    inventoryTarget: 2,
    wishlistSize: 0,
    favoritesSize: 0,
    defaultPlan: "free",
    profile: {
      publishesPerWeek: 2,
      averageListings: 12,
      averageOrderValueCents: 2500,
      returnsAfterDays: 14,
      favoriteRarity: "common",
      preferredLanguage: "pt",
      preferredCondition: "NM",
      foilPreference: "nonfoil",
      competitiveFormat: null,
      collectionFocus: ["singles"],
    },
  },
  collector: {
    id: "collector",
    label: "Collector",
    role: "collector",
    behavior: "collectorOnly",
    inventoryTarget: 0,
    wishlistSize: 3,
    favoritesSize: 2,
    defaultPlan: null,
    profile: {
      publishesPerWeek: 0,
      averageListings: 0,
      averageOrderValueCents: 15000,
      returnsAfterDays: 7,
      favoriteRarity: "enchanted",
      preferredLanguage: "en",
      preferredCondition: "NM",
      foilPreference: "foil",
      competitiveFormat: null,
      collectionFocus: ["enchanted", "iconic", "promo"],
    },
  },
  competitive: {
    id: "competitive",
    label: "Competitive Player",
    role: "buyer",
    behavior: "buyerOnly",
    inventoryTarget: 0,
    wishlistSize: 4,
    favoritesSize: 0,
    defaultPlan: null,
    profile: {
      publishesPerWeek: 0,
      averageListings: 0,
      averageOrderValueCents: 4500,
      returnsAfterDays: 2,
      favoriteRarity: "rare",
      preferredLanguage: "any",
      preferredCondition: "NM",
      foilPreference: "nonfoil",
      competitiveFormat: "constructed",
      collectionFocus: ["staples"],
    },
  },
  casual: {
    id: "casual",
    label: "Casual Player",
    role: "hybrid",
    behavior: "hybrid",
    inventoryTarget: 1,
    wishlistSize: 2,
    favoritesSize: 1,
    defaultPlan: "free",
    profile: {
      publishesPerWeek: 1,
      averageListings: 5,
      averageOrderValueCents: 1800,
      returnsAfterDays: 10,
      favoriteRarity: "uncommon",
      preferredLanguage: "pt",
      preferredCondition: "LP",
      foilPreference: "any",
      competitiveFormat: null,
      collectionFocus: ["fun", "theme"],
    },
  },
  buyer: {
    id: "buyer",
    label: "Buyer",
    role: "buyer",
    behavior: "buyerOnly",
    inventoryTarget: 0,
    wishlistSize: 2,
    favoritesSize: 0,
    defaultPlan: null,
    profile: {
      publishesPerWeek: 0,
      averageListings: 0,
      averageOrderValueCents: 3200,
      returnsAfterDays: 5,
      favoriteRarity: "any",
      preferredLanguage: "pt",
      preferredCondition: "NM",
      foilPreference: "any",
      competitiveFormat: null,
      collectionFocus: ["staples"],
    },
  },
};

export function getArchetype(id: PersonaArchetype["id"]): PersonaArchetype {
  return ARCHETYPES[id];
}
